version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3.5.7-management
    container_name: microservices
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
