spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DmitryLych/microservices-demo
          search-paths: config-data
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001
